# Generated by Django 2.1.5 on 2019-03-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_auto_20190331_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgets',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
    ]
