# Generated by Django 2.1.5 on 2019-04-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_budgets_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='last_transaction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
