# Generated by Django 2.1.5 on 2019-03-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='public_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
