# Generated by Django 2.1.5 on 2019-03-30 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_public_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='public_key',
            new_name='publicKey',
        ),
    ]
