# Generated by Django 2.1.5 on 2019-03-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190330_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='publicKey',
            new_name='accessToken',
        ),
    ]
