# Generated by Django 2.1.5 on 2019-04-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190330_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='userId',
            new_name='user',
        ),
    ]
