# Generated by Django 2.1.5 on 2019-03-30 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_name', models.CharField(max_length=100)),
                ('transaction_datetime', models.DateField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts')),
            ],
        ),
    ]
