# Generated by Django 2.1.5 on 2019-03-31 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'managed': (True,)},
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_type',
            new_name='transaction_category',
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='transactions',
        ),
    ]
