# Generated by Django 2.1.5 on 2019-03-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20190331_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='plaid_transaction_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
