# Generated by Django 2.1.5 on 2019-03-30 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=50)),
                ('transaction_portion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('benchmark_date', models.DateTimeField(auto_now=True)),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jars.Jars')),
            ],
            options={
                'db_table': 'jar_transactions',
                'managed': True,
            },
        ),
    ]
