# Generated by Django 2.1.5 on 2019-04-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jartransactions',
            name='transaction_category',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
