# Generated by Django 2.1.5 on 2019-04-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0002_jars_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jars',
            name='jar_fraction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
