# Generated by Django 2.1.5 on 2019-04-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0003_jars_jar_fraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jars',
            old_name='userId',
            new_name='user',
        ),
    ]
